import type { Kysely } from 'kysely'
import { sql } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createTable('oauth_clients')
    .ifNotExists()
    .addColumn('id', 'uuid', col => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('updated', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('client_id', 'text', col => col.unique().notNull())
    .addColumn('client_name', 'text', col => col.notNull())
    .addColumn('redirect_uris', sql`text[]`, col => col.notNull())
    .addColumn('grant_types', sql`text[]`, col => col.notNull()
      .defaultTo(sql`ARRAY['authorization_code','refresh_token']::text[]`))
    .addColumn('token_endpoint_auth_method', 'text', col => col.notNull().defaultTo('none'))
    .addColumn('scope', 'text', col => col.notNull().defaultTo(''))
    .addColumn('dynamic', 'boolean', col => col.notNull().defaultTo(true))
    .addColumn('enabled', 'boolean', col => col.notNull().defaultTo(true))
    .addColumn('created_by', 'uuid', col => col.references('users.id'))
    .execute()

  await db.schema
    .createTable('oauth_token_families')
    .ifNotExists()
    .addColumn('family_id', 'uuid', col => col.primaryKey())
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('revoked', 'boolean', col => col.notNull().defaultTo(false))
    .addColumn('revoked_reason', 'text')
    .addColumn('revoked_at', 'timestamptz')
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema
    .createTable('oauth_pending_requests')
    .ifNotExists()
    .addColumn('id', 'uuid', col => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('expires', 'timestamptz', col => col.notNull())
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('redirect_uri', 'text', col => col.notNull())
    .addColumn('scope', 'text', col => col.notNull())
    .addColumn('resource', 'text', col => col.notNull())
    .addColumn('state', 'text')
    .addColumn('code_challenge', 'text', col => col.notNull())
    .addColumn('csrf_token_hash', 'text', col => col.notNull())
    .addColumn('consumed', 'boolean', col => col.notNull().defaultTo(false))
    .execute()

  await db.schema
    .createTable('oauth_authorization_codes')
    .ifNotExists()
    .addColumn('code_hash', 'text', col => col.primaryKey())
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('redirect_uri', 'text', col => col.notNull())
    .addColumn('scope', 'text', col => col.notNull())
    .addColumn('resource', 'text', col => col.notNull())
    .addColumn('code_challenge', 'text', col => col.notNull())
    .addColumn('family_id', 'uuid', col => col.notNull().references('oauth_token_families.family_id'))
    .addColumn('expires', 'timestamptz', col => col.notNull())
    .addColumn('used', 'boolean', col => col.notNull().defaultTo(false))
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema
    .createTable('oauth_access_tokens')
    .ifNotExists()
    .addColumn('token_hash', 'text', col => col.primaryKey())
    .addColumn('id', 'uuid', col => col.notNull().unique().defaultTo(sql`gen_random_uuid()`))
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('scope', 'text', col => col.notNull())
    .addColumn('resource', 'text', col => col.notNull())
    .addColumn('family_id', 'uuid', col => col.notNull().references('oauth_token_families.family_id'))
    .addColumn('expires', 'timestamptz', col => col.notNull())
    .addColumn('revoked', 'boolean', col => col.notNull().defaultTo(false))
    .addColumn('revoked_reason', 'text')
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('last_used', 'timestamptz')
    .execute()

  await db.schema
    .createTable('oauth_refresh_tokens')
    .ifNotExists()
    .addColumn('token_hash', 'text', col => col.primaryKey())
    .addColumn('id', 'uuid', col => col.notNull().unique().defaultTo(sql`gen_random_uuid()`))
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('scope', 'text', col => col.notNull())
    .addColumn('resource', 'text', col => col.notNull())
    .addColumn('family_id', 'uuid', col => col.notNull().references('oauth_token_families.family_id'))
    .addColumn('rotated_from_id', 'uuid')
    .addColumn('access_token_id', 'uuid', col => col.references('oauth_access_tokens.id').onDelete('set null'))
    .addColumn('expires', 'timestamptz', col => col.notNull())
    .addColumn('used', 'boolean', col => col.notNull().defaultTo(false))
    .addColumn('revoked', 'boolean', col => col.notNull().defaultTo(false))
    .addColumn('revoked_reason', 'text')
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema
    .createTable('oauth_consents')
    .ifNotExists()
    .addColumn('id', 'uuid', col => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('created', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('updated', 'timestamptz', col => col.notNull().defaultTo(sql`now()`))
    .addColumn('client_id', 'text', col => col.notNull().references('oauth_clients.client_id'))
    .addColumn('user_id', 'uuid', col => col.notNull().references('users.id').onDelete('cascade'))
    .addColumn('resource', 'text', col => col.notNull())
    .addColumn('scope', 'text', col => col.notNull())
    .addColumn('revoked', 'boolean', col => col.notNull().defaultTo(false))
    .execute()

  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_codes_expires ON oauth_authorization_codes(expires)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_codes_family ON oauth_authorization_codes(family_id)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_access_user ON oauth_access_tokens(user_id)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_access_expires ON oauth_access_tokens(expires)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_access_family ON oauth_access_tokens(family_id)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_refresh_family ON oauth_refresh_tokens(family_id)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_pending_expires ON oauth_pending_requests(expires)`.execute(db)
  await sql`CREATE INDEX IF NOT EXISTS idx_oauth_families_user ON oauth_token_families(user_id)`.execute(db)
  await sql`CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_consents_cur ON oauth_consents(client_id, user_id, resource)`.execute(db)
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('oauth_consents').ifExists().execute()
  await db.schema.dropTable('oauth_refresh_tokens').ifExists().execute()
  await db.schema.dropTable('oauth_access_tokens').ifExists().execute()
  await db.schema.dropTable('oauth_authorization_codes').ifExists().execute()
  await db.schema.dropTable('oauth_pending_requests').ifExists().execute()
  await db.schema.dropTable('oauth_token_families').ifExists().execute()
  await db.schema.dropTable('oauth_clients').ifExists().execute()
}
